spring.application.name=sb-ecom
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

#Image path
project.upload.path=images/

# Enable SQL logging
#spring.jpa.show-sql=true

# Format the SQL output (optional but helpful)
spring.jpa.properties.hibernate.format_sql=true

# (Optional) Log SQL with parameter values, not just '?'
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#logging.level.org.hibernate.SQL=DEBUG

# Db username/password
spring.datasource.username=sa
spring.datasource.password=
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000

#Cookie
spring.com.app.jwtCookieName=springBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG

#Let Spring Boot Use Built-in Schema (Recommended) This requires NO custom SQL file, j
# ust these lines in application.properties:
#If your file name is schema.sql, Spring will auto-detect it.But if you name it something else (like test.sql),
# then you must specify in "schema-locations=?":
spring.sql.init.mode=always

#spring.sql.init.schema-locations=classpath:org/springframework/security/core/userdetails/jdbc/users.ddl



